apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS cartdb;
    CREATE DATABASE IF NOT EXISTS reviewdb;
    CREATE DATABASE IF NOT EXISTS admindb;
    CREATE DATABASE IF NOT EXISTS productdb;
    CREATE DATABASE IF NOT EXISTS paymentdb;
    CREATE DATABASE IF NOT EXISTS orderdb;
    CREATE DATABASE IF NOT EXISTS messagingdb;